Add source file name to database
farsightsec/dnstable-convert pull request #14
Opened 2024-01-05 19:38 UTC by dvladi77

2024-01-05 20:31 UTC, cmikk requested changes
Requesting a change to `-S` to _enable_ the source tracking rather than disable, for flexibility in releasing this code.

Please also update the manual page for the new options.

2024-01-05 20:31 UTC, cmikk commented on dnstable_convert.c
> +			store_nmsg_source = false;
Please reverse the sense of `-S` here, so `dnstable_convert` defaults to its old behavior.

2024-01-05 20:31 UTC, cmikk commented on dnstable_convert.c
> +			nmsg_source_fname = strdup(optarg);
Since `nmsg_source_fname` isn't modified, you should be able to save `optarg` (or `nmsg_fname` below) directly without `strdup`.

2024-01-08 20:49 UTC, cmikk approved these changes
I pushed one whitespace change and a fix to a compiler warning.

This looks good for a squash merge.

2024-01-08 21:19 UTC, shw700 approved these changes

2024-01-09 17:04 UTC, merged